# fly.toml app configuration file generated for ecoride-crimson-sun-5659 on 2025-05-12T03:01:56+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ecoride-crimson-sun-5659'
primary_region = 'cdg'

[build]

[[services]]
  internal_port = 80
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls","http"]
    port = 443

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
